version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/romashka2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 79182872449
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: romashka2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 79182872449
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge